# -*- coding: utf-8 -*-
"""python_git_exp1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13Z06ydOQQwKaXRvruIifO7v7nUCW0dWH
"""

#1 ques already done ,  Install Python and write the steps of installation and understand difference between scripting and
interactive modes in IDLE

#2 ques Create a variable to store your age and print its type using type().
age = 20
print(type(age))

#3 ques Declare a string variable called x and assign it the value “Hello”.
#a. Print out the value of x
x = "Hello"
print(x)

#4 ques Take different data types and print values using print function
a = 10
b = 3.5
c = "Python"
d = True

print(a)
print(b)
print(c)
print(d)

#5 ques Declare these variables (x, y and z) as integers. Assign a value of 9 to x, Assign a value of 7 to y, perform
#addition, multiplication, division and subtraction on these two variables and Print out the result.
x = 9
y = 7

print("Addition =", x + y)
print("Multiplication =", x * y)
print("Division =", x / y)
print("Subtraction =", x - y)

#6 ques Write a program to compute the length of the hypotenuse (c) of a right triangle using Pythagoras
#theorem.
a = float(input("Enter first side: "))
b = float(input("Enter second side: "))

c = (a*a + b*b) ** 0.5

print("Hypotenuse =", c)

#7 ques Write a program to find simple interest.
p = float(input("Enter principal: "))
r = float(input("Enter rate: "))
t = float(input("Enter time: "))

si = (p * r * t) / 100

print("Simple Interest =", si)

#8 ques (using importing maths) Write a program to find area of triangle when length of sides are given
import math

a = float(input("Enter side 1: "))
b = float(input("Enter side 2: "))
c = float(input("Enter side 3: "))

s = (a + b + c) / 2

area = math.sqrt(s * (s - a) * (s - b) * (s - c))

print("Area of triangle =", area)

#8 ques (without using importing maths) Write a program to find area of triangle when length of sides are given
a = float(input("Enter side 1: "))
b = float(input("Enter side 2: "))
c = float(input("Enter side 3: "))

s = (a + b + c) / 2

area = (s * (s - a) * (s - b) * (s - c)) ** 0.5

print("Area of triangle =", area)

#9 ques Write a program to convert given seconds into hours, minutes and remaining seconds
seconds = int(input("Enter seconds: "))

hours = seconds // 3600
minutes = (seconds % 3600) // 60
remaining = seconds % 60

print("Hours =", hours)
print("Minutes =", minutes)
print("Seconds =", remaining)

#10 ques Write a program to swap two numbers without taking additional variable.

a = int(input("Enter first number: "))
b = int(input("Enter second number: "))

a = a + b
b = a - b
a = a - b

print("After swapping:")
print("a =", a)
print("b =", b)

#11 ques Write a program to find sum of first n natural numbers.
n = int(input("Enter value of n: "))

sum = 0

for i in range(1, n + 1):
    sum = sum + i

print("Sum =", sum)

#12 ques Write a program to print truth table for bitwise operators (&, | and ^ operators)
print("A B A&B A|B A^B")

for i in range(2):
    for j in range(2):
        print(i, j, i & j, i | j, i ^ j)

#13 ques Write a program to find left shift and right shift values of a given number.
num = int(input("Enter a number: "))
shift = int(input("Enter shift value: "))

print("Left Shift =", num << shift)
print("Right Shift =", num >> shift)

#14 ques Using membership operator find whether a given number is in sequence (10,20,56,78,89)
num = int(input("Enter a number: "))

seq = (10, 20, 56, 78, 89)

print(num in seq)